# ***VOCÊ É UM DEV E PRECISA CRIAR UM SISTEMA PARA UMA ESCOLA.*** 
# ***SISTEMA DE NOTAS DE ALUNOS QUE MOSTRE COM ESTATISTICA A MODA ,  MEDIA, MEDIANA E DESVIO DE PADRÃO, DAS NOTAS DE ALUNOS DE UM COLÉGIO, ALÉM DE MOSTRAR  A MENOR E A  MAIOR NOTA, SEPARE EM FUNÇÕES DIFERENTES, CRIE MÓDULOS.***  
# ***1 - VOCÊ CRIAR SEUS PRÓPRIOS MÓDULOS***
# ***2 - OU USAR STATISTICS(com módulos)*** 
# ***3 - Utilize Parâmetros, caso deixe mais flexível***

